---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
        timeout: 600
    - name: "install python for Ansible."
      become: yes
      apt:
        name: "python3-pip"
        update_cache: yes
        state: present
    - name: 'Wait port 22 to become reachable/usable.'
      wait_for:
        port: 22
        delay: 10

  roles:
    - configure-server
    - configure-prometheus-node-exporter