version: 2.1

orbs:
  slack: circleci/slack@4.1.1
 # ---------------------------------------------------------------------------- #
 #                              Slack Notifications                             #
 # ---------------------------------------------------------------------------- #

  commands:
    slack-notification-fail:
     steps:
       - slack/notify:
          event: fail
          channel: MohamedAwwad
  
   

# ---------------------------------------------------------------------------- #
#                                 Jobs Section                                 #
# ---------------------------------------------------------------------------- #

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Install prerequsites
          command: |            
            sudo apt -y install jq tar gzip git curl

      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          key: v1-frontend-build
          paths:
            - ~/project/frontend/node_modules
      - slack-notification-fail

  build-backend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Install prerequsites
          command: |
            sudo apt -y install jq tar gzip git curl

      - run:
          name: Backend build
          command: |
            cd backend
            npm i
            npm run build

      - save_cache:
          key: v1-backend-build
          paths:
            - ~/project/backend/node_modules
      - slack-notification-fail


  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: frontend test
          command: |
            cd frontend
            npm i
            npm run test  
      - slack-notification-fail

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: backend test
          command: |
            cd backend
            npm install
            npm test
      - slack-notification-fail

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: frontend scan
          command: |
            cd frontend
            npm audit --audit-level=critical
      - slack-notification-fail

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: backend scan
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack-notification-fail 


notify_on_sucess:
    docker:
      - image: cimg/bash:stable
    steps:
      - slack/notify:
          event: pass
          channel: MohamedAwwad
          template: sucess_tagged_deployment_1

workflows:
  default:
     jobs:
      - build-frontend
         
      - build-backend
         
          
      - test-frontend:
          
          requires: [build-frontend]
      - test-backend:
          
          requires: [build-backend]
      - scan-backend:
          
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - notify_on_sucess:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      
          