version: 2.1

orbs: 
  node: circleci/node@5.0.2
  slack: circleci/slack@4.9.4


commands:
  notify_on_failure:
    steps:
      - slack/notify:
          channel: C03EM7RJMPC
          event: fail
          template: basic_fail_1


jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-depnd]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-depnd
      - notify_on_failure

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-depnd]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build 
      - save_cache:
          paths: [backend/node_modules]
          key: backend-depnd
      - notify_on_failure

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-depnd]
      - run:
          name: Frontend unit test
          command: |
            cd frontend
            npm install
            npm test 
  test-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-depnd]
      - run:
          name: Backend unit test
          command: |
            cd backend
            npm install
            npm test
      - notify_on_failure

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-depnd]
      - run:
          name: Frontend scan
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - notify_on_failure

  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-depnd]
      - run:
          name: Backend scan
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - notify_on_failure


  notify_on_success:
    docker:
      - image: cimg/base:2022.04
    steps:
      - slack/notify:
          channel: C03EM7RJMPC
          event: pass
          template: success_tagged_deploy_1




workflows:
  udapeople-flow:
    jobs:
      - notify_on_success:
          requires: 
            - build-frontend
            - build-backend
            - test-frontend
            - test-backend
            - scan-backend
            - scan-frontend
            # - deploy-infrastructure
            # - run-migrations
            # - deploy-frontend
            # - deploy-backend
            # - smoke-test
            # - cloudfront-update
            # - cleanup









