version: 2.1

orbs:
  slack: circleci/slack@4.9.3
 # ---------------------------------------------------------------------------- #
 #                              Slack Notifications                             #
 # ---------------------------------------------------------------------------- #

  commands:
  #  slack-notification-fail:
  #    steps:
  #      - slack/notify:
  #         event: fail
  #         channel: MohamedAwwad
  
   slack-notification-fail:
    description: Send notification to Slack
    steps:
      - extract-commit-message

      - slack/notify:
          channel: MohamedAwwad
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *faild* :octagonal_sign: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME\n\ncommit message: $COMMIT_MESSAGE"
                  }
                }
              ]
            }
  slack-notification-pass:
    description: Send notification to Slack
    steps:
      - extract-commit-message

      - slack/notify:
          channel: MohamedAwwad
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *built* :white_check_mark: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME\n\ncommit message: $COMMIT_MESSAGE"
                  }
                }
              ]
            }

# ---------------------------------------------------------------------------- #
#                                 Jobs Section                                 #
# ---------------------------------------------------------------------------- #

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Install prerequsites
          command: |            
            sudo apt -y install jq tar gzip git curl

      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          key: v1-frontend-build
          paths:
            - ~/project/frontend/node_modules
      - slack-notification-fail

  build-backend:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      - run:
          name: Install prerequsites
          command: |
            sudo apt -y install jq tar gzip git curl

      - run:
          name: Backend build
          command: |
            cd backend
            npm i
            npm run build

      - save_cache:
          key: v1-backend-build
          paths:
            - ~/project/backend/node_modules
      - slack-notification-fail


  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: frontend test
          command: |
            cd frontend
            npm i
            npm run test  
      - slack-notification-fail

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: backend test
          command: |
            cd backend
            npm install
            npm test
      - slack-notification-fail

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: frontend scan
          command: |
            cd frontend
            npm audit --audit-level=critical
      - slack-notification-fail

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: backend scan
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack-notification-fail 


notify_on_sucess:
    docker:
      - image: cimg/bash:stable
    steps:
      - slack/notify:
          event: pass
          channel: MohamedAwwad
          template: sucess_tagged_deployment_1

workflows:
  default:
     jobs:
      - build-frontend:
         context: slack
      - build-backend:
         context: slack
          
      - test-frontend:
          context: slack
          requires: [build-frontend]
      - test-backend:
          context: slack
          requires: [build-backend]
      - scan-backend:
          context: slack
          requires: [build-backend]
      - scan-frontend:
          context: slack
          requires: [build-frontend]
      
          